#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Dec 31 12:11:52 MST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
